# The service name of the XMPP server.
service: example.com

# The username the plugin should use to connect on the server.
username: user

# The password of the user defined above.
password: pass

# The nickname under which MCXMPP will appear in MUC rooms.
nickname: MCXMPP

# MCXMPP joins a MUC (Multi-User Chat) room after connection.
# This is the JID of the room to join.
room: myroom@conference.example.com

# If the room is password-protected, or if you want it to be password-protected, set the password here.
#room-password: roompass

# Chat formatting for messages sent from XMPP
# Available variables :
# %sender - sender
# %message - message body
mc-chat-format: '<(&cXMPP&f)%sender> %message'

# Chat formatting for messages sent from Minecraft
# Available variables :
# %sender - sender
# %message - message body
# %prefix - Vault prefix
# %suffix - Vault suffix
# %world - world from which the sender sent the message
xmpp-chat-format: '<[%world] %prefix %sender %suffix> %message'
