name: MCXMPP
main: tk.torche.plugin.MCXMPP
version: 0.5.2.0
author: Coproglotte
softdepend: ['Vault']

commands:
  mcxmpp:
    description: 'Global MCXMPP plugin commands'
    usage: '/<command> help'
    aliases: [xmpp]

permissions:
  mcxmpp.admin:
    description: Gives admin powers to the player
    default: false
    children:
      mcxmpp.notice: true

  mcxmpp.notice:
    description: Allows to receive notices from the plugin
    default: false

  mcxmpp.ignore.*:
    description: Ignore every possible action from the player
    default: false
    children:
      mcxmpp.ignore.commands: true
      mcxmpp.ignore.messages: true
      mcxmpp.ignore.joinquite: true

  mcxmpp.ignore.commands:
    description: Ignore commands sent
    default: false

  mcxmpp.ignore.messages:
    description: Ignore messages sent
    default: false

  mcxmpp.ignore.joinquit:
    description: Ignore join and quit events
    default: false
