# This is the XMPP server to connect to.
# It may differ from the domain name in your JID (the part after the "@").
host: example.com

# The service name of the XMPP server.
# This may be necessary on some server. It may be the same value as host.
#service: example.com

# The port to connect to the XMPP server.
# default is 5222
port: 5222

# The username the plugin should use to connect on the server.
# It mustn't be in the form "user@example.com". Just put the "user" part.
username: user

# The password of the user defined above.
password: pass

# MCXMPP joins a MUC channel (Multi-User Chat) after connection.
# This is the name of the channel to join.
channel: channelname

# If the channel is password-protected, provide the password here.
#channel-password: chanpass

# Chat formatting for messages sent from XMPP
# Available variables :
# %s - sender
# %m - message body
mc-chat-format: '<(&cXMPP&f)%s> %m'
