# The service name of the XMPP server.
service: example.com

# The username the plugin should use to connect on the server.
# It mustn't be in the form "user@example.com". Just put the "user" part.
username: user

# The password of the user defined above.
password: pass

# The nickname under which MCXMPP will appear in MUC channels.
nickname: MCXMPP

# MCXMPP joins a MUC channel (Multi-User Chat) after connection.
# This is the name of the channel to join.
channel: channelname

# If the channel is password-protected, provide the password here.
#channel-password: chanpass

# Chat formatting for messages sent from XMPP
# Available variables :
# %s - sender
# %m - message body
mc-chat-format: '<(&cXMPP&f)%s> %m'
